version: '3.8' # docker compose version

services:
  kafka:
    image: apache/kafka:3.7.0 # kafka image to download and use
    container_name: kafka # name of the container
    ports:
      - "9092:9092" # map mac port 9092 to container port 9092
    environment:
      KAFKA_NODE_ID: 1 # unique id for this broker
      KAFKA_PROCESS_ROLES: broker,controller # this node acts as both broker and controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093 # ports kafka listens on inside container
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # address kafka tells your app to connect to
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER # which listener handles cluster management
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT # no encryption (fine for local dev!)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 # who votes in cluster decisions (just us, one broker!)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # only 1 copy of offsets topic (we have 1 broker locally)
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true' # automatically create topics when first used