version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka 
    ports:
      - "9092:9092" # PLAINTEXT port for Docker containers (kafka-ui)
      - "9093:9093" # EXTERNAL port for YOUR Mac app (OrderApi)
    networks:
      - kafka-network # join shared network so kafka-ui can reach kafka
    environment:
      KAFKA_NODE_ID: 1 # unique broker ID
      KAFKA_PROCESS_ROLES: broker,controller 
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094 # ports Kafka listens on inside container
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093 # PLAINTEXT for Docker containers, EXTERNAL for Mac apps
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT # no encryption (fine for local dev!)
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER 
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true' 
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT 

  kafka-ui:
    image: provectuslabs/kafka-ui:latest 
    container_name: kafka-ui 
    ports:
      - "8080:8080"
    networks:
      - kafka-network 
    environment:
      KAFKA_CLUSTERS_0_NAME: local 
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092 
    depends_on:
      - kafka 

networks:
  kafka-network:
    driver: bridge